In this notebook, I am learning the basics of tensorflow with the help of the MNIST public database

In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 1s 0us/step


In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [23]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='sigmoid'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [24]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.1813222 ,  0.76256824, -0.18748906, -0.67479634, -0.29242197,
        -1.118814  ,  0.5670129 ,  1.0587983 ,  0.27791825,  0.5465938 ]],
      dtype=float32)

In [25]:
tf.nn.softmax(predictions).numpy()


array([[0.02444091, 0.17074114, 0.06602882, 0.04056006, 0.05945136,
        0.02601742, 0.14041372, 0.22960918, 0.10516164, 0.13757567]],
      dtype=float32)

In [26]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [27]:
loss_fn(y_train[:1], predictions).numpy()


3.648989

In [28]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [29]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4424 - accuracy: 0.8773
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2280 - accuracy: 0.9329
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1734 - accuracy: 0.9493
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1389 - accuracy: 0.9596
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1189 - accuracy: 0.9648


In [30]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.1027 - accuracy: 0.9697


[0.10272514820098877, 0.9696999788284302]

In [31]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1302083e-06, 5.7288401e-07, 4.0040959e-05, 6.3251256e-04,
        7.8082742e-08, 8.0324535e-06, 2.1599970e-10, 9.9930298e-01,
        3.1760487e-07, 1.4309514e-05],
       [1.8975499e-05, 3.3933693e-04, 9.9810326e-01, 6.4900354e-04,
        4.0828838e-09, 6.9217535e-04, 4.7135771e-05, 3.9785959e-08,
        1.5003879e-04, 2.4399098e-08],
       [8.9884765e-08, 9.9733114e-01, 7.9380168e-04, 1.8219399e-04,
        1.1502984e-05, 1.2973481e-04, 5.7509329e-05, 9.7061024e-04,
        5.1881943e-04, 4.6959126e-06],
       [9.9843961e-01, 3.7899795e-06, 3.0402213e-04, 6.2878433e-05,
        1.8498537e-05, 2.2398893e-04, 5.2066275e-04, 2.4247890e-04,
        1.1063859e-05, 1.7308736e-04],
       [3.0628762e-05, 8.5417561e-08, 2.5078567e-04, 1.2040323e-06,
        9.9556267e-01, 1.5245301e-05, 8.5784559e-05, 1.5182282e-04,
        9.4982515e-06, 3.8922671e-03]], dtype=float32)>

In [32]:
tf.math.argmax(probability_model(x_test[:5]), axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([7, 2, 1, 0, 4])>